apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: dev

images:
- name: destaxa-financial
  newName: 317427797532.dkr.ecr.sa-east-1.amazonaws.com/destaxa-financial
  newTag: "35"
  
#generators:
#- {pathOrUrl}
#- ...

#transformers:
#- {pathOrUrl}
#- ...

#validators:
#- {pathOrUrl}
#- ...